import { world, system, EquipmentSlot, GameMode, ItemStack } from "@minecraft/server";
import { repeatedUse } from "./use_guard.js";

// Segmented ground cover (golden leaf carpet, Mallorn blossoms), like vanilla leaf litter: 1-4 segments
// per block in state `lothlorien:amount`. Generated by .claude/skills/bedrock-blocks/scripts/gen_ground_cover.py.
//  - Using the item on a cover block (or on the ground where one lies) adds a segment, up to 4.
//  - Breaking a block with n segments drops n items (the block's own drop gives one).
const AMOUNT = "lothlorien:amount";
const MAX_AMOUNT = 4;
const COVERS = new Set(["lothlorien:mallorn_leaf_carpet", "lothlorien:mallorn_blossom"]);
const FACE_OFFSET = {
  Up: [0, 1, 0], Down: [0, -1, 0], North: [0, 0, -1], South: [0, 0, 1], East: [1, 0, 0], West: [-1, 0, 0],
};

world.beforeEvents.playerInteractWithBlock.subscribe((event) => {
  const { block, player, itemStack, blockFace } = event;
  if (!itemStack || !COVERS.has(itemStack.typeId)) return;
  let target = block;
  if (block.typeId !== itemStack.typeId) {
    const [dx, dy, dz] = FACE_OFFSET[blockFace];
    target = block.dimension.getBlock({ x: block.x + dx, y: block.y + dy, z: block.z + dz });
    if (target?.typeId !== itemStack.typeId) return;
  }
  const amount = target.permutation.getState(AMOUNT);
  if (typeof amount !== "number" || amount >= MAX_AMOUNT) return;
  event.cancel = true;
  if (repeatedUse(player, "merge")) return;
  system.run(() => {
    target.setPermutation(target.permutation.withState(AMOUNT, amount + 1));
    target.dimension.playSound("dig.grass", target.center());
    if (player.getGameMode() === GameMode.Creative) return;
    const slot = player.getComponent("equippable")?.getEquipmentSlot(EquipmentSlot.Mainhand);
    if (!slot?.hasItem()) return;
    if (slot.amount > 1) slot.amount -= 1;
    else slot.setItem(undefined);
  });
});

// Bedrock kills grass under any custom partial block in low light, whatever its light_dampening
// (MCPE-184249); under the Mallorn canopy it is always dark enough. The cover therefore turns plain
// dirt below it back into grass, but only next to grass (as if spread), so a dirt floor someone
// covered on purpose stays dirt. `minecraft:tick` (15-30 s) bounds how long dirt shows;
// random ticks alone run at the decay rate and would leave about half of it dirt.
const KEEP_GRASS_NEIGHBOURS = [[1, 0], [-1, 0], [0, 1], [0, -1], [1, 1], [1, -1], [-1, 1], [-1, -1]];

function keepGrass({ block, dimension }) {
  try {
    const below = block.below();
    if (below?.typeId !== "minecraft:dirt") return;
    const { x, y, z } = below.location;
    for (const dy of [0, -1, 1]) {
      for (const [dx, dz] of KEEP_GRASS_NEIGHBOURS) {
        if (dimension.getBlock({ x: x + dx, y: y + dy, z: z + dz })?.typeId !== "minecraft:grass_block") continue;
        below.setType("minecraft:grass_block");
        return;
      }
    }
  } catch {
    // neighbour in an unloaded chunk or outside the world: try again next tick
  }
}

system.beforeEvents.startup.subscribe(({ blockComponentRegistry }) => {
  blockComponentRegistry.registerCustomComponent("lothlorien:keep_grass", { onTick: keepGrass, onRandomTick: keepGrass });
});

world.afterEvents.playerBreakBlock.subscribe(({ player, dimension, block, brokenBlockPermutation }) => {
  if (!COVERS.has(brokenBlockPermutation.type.id) || player.getGameMode() === GameMode.Creative) return;
  const amount = brokenBlockPermutation.getState(AMOUNT);
  if (typeof amount !== "number" || amount < 2) return;
  dimension.spawnItem(new ItemStack(brokenBlockPermutation.type.id, amount - 1), block.center());
});
