import { world, system, EquipmentSlot, GameMode, ItemStack } from "@minecraft/server";

// Segmented ground cover (golden leaf carpet, Mallorn blossoms), like vanilla leaf litter: 1-4 segments
// per block in state `lothlorien:amount`. Generated by .claude/skills/bedrock-blocks/scripts/gen_ground_cover.py.
//  - Using the item on a cover block (or on the ground where one lies) adds a segment, up to 4.
//  - Breaking a block with n segments drops n items (the block's own drop gives one).
const AMOUNT = "lothlorien:amount";
const MAX_AMOUNT = 4;
const COVERS = new Set(["lothlorien:mallorn_leaf_carpet", "lothlorien:mallorn_blossom"]);
const FACE_OFFSET = {
  Up: [0, 1, 0], Down: [0, -1, 0], North: [0, 0, -1], South: [0, 0, 1], East: [1, 0, 0], West: [-1, 0, 0],
};

world.beforeEvents.playerInteractWithBlock.subscribe((event) => {
  const { block, player, itemStack, blockFace } = event;
  if (!itemStack || !COVERS.has(itemStack.typeId)) return;
  let target = block;
  if (block.typeId !== itemStack.typeId) {
    const [dx, dy, dz] = FACE_OFFSET[blockFace];
    target = block.dimension.getBlock({ x: block.x + dx, y: block.y + dy, z: block.z + dz });
    if (target?.typeId !== itemStack.typeId) return;
  }
  const amount = target.permutation.getState(AMOUNT);
  if (typeof amount !== "number" || amount >= MAX_AMOUNT) return;
  event.cancel = true;
  system.run(() => {
    target.setPermutation(target.permutation.withState(AMOUNT, amount + 1));
    target.dimension.playSound("dig.grass", target.center());
    if (player.getGameMode() === GameMode.Creative) return;
    const slot = player.getComponent("equippable")?.getEquipmentSlot(EquipmentSlot.Mainhand);
    if (!slot?.hasItem()) return;
    if (slot.amount > 1) slot.amount -= 1;
    else slot.setItem(undefined);
  });
});

world.afterEvents.playerBreakBlock.subscribe(({ player, dimension, block, brokenBlockPermutation }) => {
  if (!COVERS.has(brokenBlockPermutation.type.id) || player.getGameMode() === GameMode.Creative) return;
  const amount = brokenBlockPermutation.getState(AMOUNT);
  if (typeof amount !== "number" || amount < 2) return;
  dimension.spawnItem(new ItemStack(brokenBlockPermutation.type.id, amount - 1), block.center());
});
